// Define chapter counts for each book
export const CHAPTER_COUNTS = {
  // Old Testament
  Genesis: 50,
  Exodus: 40,
  Leviticus: 27,
  Numbers: 36,
  Deuteronomy: 34,
  Joshua: 24,
  Judges: 21,
  Ruth: 4,
  '1 Samuel': 31,
  '2 Samuel': 24,
  '1 Kings': 22,
  '2 Kings': 25,
  '1 Chronicles': 29,
  '2 Chronicles': 36,
  Ezra: 10,
  Nehemiah: 13,
  Esther: 10,
  Job: 42,
  Psalms: 150,
  Proverbs: 31,
  Ecclesiastes: 12,
  'Song of Solomon': 8,
  Isaiah: 66,
  Jeremiah: 52,
  Lamentations: 5,
  Ezekiel: 48,
  Daniel: 12,
  Hosea: 14,
  Joel: 3,
  Amos: 9,
  Obadiah: 1,
  Jonah: 4,
  Micah: 7,
  Nahum: 3,
  Habakkuk: 3,
  Zephaniah: 3,
  Haggai: 2,
  Zechariah: 14,
  Malachi: 4,

  // New Testament
  Matthew: 28,
  Mark: 16,
  Luke: 24,
  John: 21,
  Acts: 28,
  Romans: 16,
  '1 Corinthians': 16,
  '2 Corinthians': 13,
  Galatians: 6,
  Ephesians: 6,
  Philippians: 4,
  Colossians: 4,
  '1 Thessalonians': 5,
  '2 Thessalonians': 3,
  '1 Timothy': 6,
  '2 Timothy': 4,
  Titus: 3,
  Philemon: 1,
  Hebrews: 13,
  James: 5,
  '1 Peter': 5,
  '2 Peter': 3,
  '1 John': 5,
  '2 John': 1,
  '3 John': 1,
  Jude: 1,
  Revelation: 22,

  // Myanmar Bible
  'ကမ္ဘာဦးကျမ်း': 50,
  'ထွက်မြောက်ရာကျမ်း။': 40,
  'ဝတ်ပြုရာကျမ်း': 27,
  'တောလည်ရာကျမ်း': 36,
  'တရားဟောရာကျမ်း': 34,
  'ယောရှုမှတ်စာ။': 24,
  'တရားသူကြီးမှတ်စာ': 21,
  'ရုသဝတ္ထု။': 4,
  'ဓမ္မရာဇဝင်​‌ပဋ္ဌမစောင်': 31,
  'ဓမ္မရာဇဝင်​‌ဒုတိယစောင်။': 24,
  'ဓမ္မရာဇဝင်​တတိယစောင်။': 22,
  'ဓမ္မရာဇဝင်​‌စတုတ္ထစောင်။': 25,
  'ရာဇဝင်ချုပ်​ပဌမစောင်။': 29,
  'ရာဇဝင်ချုပ်​ဒုတိယစောင်။': 36,
  'ဧဇရမှတ်စာ။': 10,
  'နေဟမိမှတ်စာ။': 13,
  'ဧသတာဝတ္ထု။': 10,
  'ယောဘဝတ္ထု။': 42,
  'ဆာလံကျမ်း': 150,
  'သုတ္တံကျမ်း။': 31,
  'ဒေသနာကျမ်း။': 12,
  'ရှောလမုန်သီချင်း။': 8,
  'ဟေရှာယအနာဂတ္တိကျမ်း။': 66,
  'ယေရမိအနာဂတ္တိကျမ်း။': 52,
  'ယေရမိမြည်တမ်းစကား။': 5,
  'ယေဇကျေလအနာဂတ္တိကျမ်း။ ၁': 48,
  'ဒံယေလအနာဂတ္တိကျမ်း။': 12,
  'ဟောရှေအနာဂတ္တိကျမ်း': 14,
  'ယောလအနာဂတ္တိကျမ်း။': 3,
  'အာမုတ်အနာဂတ္တိကျမ်း။': 9,
  'ဩဗဒိဗျာဒိတ်ရူပါရုံ': 1,
  'ယောနဝတ္ထု၊': 4,
  'မိက္ခာအနာဂတ္တိကျမ်း။': 7,
  'နာဟုံအနာဂတ္တိကျမ်း': 3,
  'ဟဗက္ကုတ်အနာဂတ္တိကျမ်း': 3,
  'ဇေဖနိအနာဂတ္တိကျမ်း': 3,
  'ဟဂ္ဂဲအနာဂတ္တိကျမ်း': 2,
  'ဇာခရိအနာဂတ္တိကျမ်း': 14,
  'မာလခိအနာဂတ္တိကျမ်း': 4,
  'ရှင်မဿဲခရစ်ဝင်။': 28,
  'ရှင်မာကုခရစ်ဝင်။': 16,
  'ရှင်လုကာခရစ်ဝင်။': 24,
  'ရှင်ယောဟန်ခရစ်ဝင်။': 21,
  'တမန်တော်ဝတ္ထု။': 28,
  'ရောမ​ဩဝါဒစာ။': 16,
  'ကောရိန္သု​ဩဝါဒစာ​ပဌမစောင်။': 16,
  'ကောရိန္သု​ဩဝါသစာ​ဒုတိယစောင်။': 13,
  'ဂလာတိ​ဩဝါဒစာ။': 6,
  'ဧဖက်​ဩဝါဒစာ။': 6,
  'ဖိလိပ္ပိ​ဩဝါဒစာ။': 4,
  'ကောလောသဲ​ဩဝါဒစာ': 4,
  'သက်သာလောနိတ်​ဩဝါဒစာ​ပဋ္ဌမစောင်': 5,
  'သက်သာလောနိတ်​ဩဝါဒစာ​ဒုတိယစောင်': 3,
  'တိမောသေ​ဩဝါဒစာ​ပဋ္ဌမစောင်': 6,
  'တိမောသေ​ဩဝါဒစာ​ဒုတိယစောင်': 4,
  'တိတု​ဩဝါဒစာ': 3,
  'ဖိလေမုန်​ဩဝါဒစာ။': 1,
  'ဟေဗြဲ​ဩဝါဒစာ။': 13,
  'ရှင်ယာကုပ်​‌ဩဝါဒစာ။': 5,
  'ရှင်ပေတရု​ဩဝါဒစာ​ပဌမစောင်။': 5,
  'ရှင်ပေတရု​ဩဝါဒစာ​ဒုတိယစောင်။': 3,
  'ရှင်ယောဟန်​‌ဩဝါဒစာ​ပဌမစောင်။': 5,
  'ရှင်ယောဟန်​‌ဩဝါဒစာ​ဒုတိယစောင်။': 1,
  'ရှင်ယောဟန်​‌ဩဝါဒစာ​တတိယစောင်။': 1,
  'ရှင်ယုဒ​ဩဝါဒစာ။': 1,
  'ဗျာဒိတ်ကျမ်း။': 22,

  // Hakha Chin Bible
  'GENESIS': 50,
  'EXODUS': 40,
  'LEVITIKAS': 27,
  'NAMBAR': 36,
  'DEUTERONOMI': 34,
  'JOSHUA': 24,
  'BIACEIHTU': 21,
  'RUTH': 4,
  '1 SAMUEL': 31,
  '2 SAMUEL': 24,
  '1 SIANGPAHRANG': 22,
  '2 SIANGPAHRANG': 25,
  '1 CHANRELNAK': 29,
  '2 CHANRELNAK': 36,
  'EZRA': 10,
  'NEHEMIAH': 13,
  'ESTHER': 10,
  'JOB': 42,
  'SALM': 150,
  'PHUNGTHLUKBIA': 31,
  'PHUNGCHIMTU': 12,
  'SOLOMON HLA': 8,
  'ISAIAH': 66,
  'JEREMIAH': 52,
  'ṬAHNAK HLA': 5,
  'EZEKIEL': 48,
  'DANIEL': 12,
  'HOSEA': 14,
  'JOEL': 3,
  'AMOS': 9,
  'OBADIAH': 1,
  'JONAH': 4,
  'MIKAH': 7,
  'NAHUM': 3,
  'HABAKKUK': 3,
  'ZEFANIAH': 3,
  'HAGGAI': 2,
  'ZEKHARIAH': 14,
  'MALAKHI': 4,
  'MATTHAI': 28,
  'MARKA': 16,
  'LUKA': 24,
  'JOHAN': 21,
  'LAMKALTU': 28,
  'ROM': 16,
  '1 KORIN': 16,
  '2 KORIN': 13,
  'GALATI': 6,
  'EFESA': 6,
  'FILIPI': 4,
  'KOLOSE': 4,
  '1 THESALON': 5,
  '2 THESALON': 3,
  '1 TIMOTE': 6,
  '2 TIMOTE': 4,
  'TITAS': 3,
  'FILEMON': 1,
  'HEBRU': 13,
  'JEIM': 5,
  '1 PETER': 5,
  '2 PETER': 3,
  '1 JOHAN': 5,
  '2 JOHAN': 1,
  '3 JOHAN': 1,
  'JUDAS': 1,
  'BIATHLAM': 22,
 } as const;

// Helper function to get chapter count for any book in any version
export function getChapterCount(book: string): number {
  return (CHAPTER_COUNTS as any)[book] || 50; // Default to 50 if not found
}